/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package net.varionic.cloudbase

import kotlin.test.*

import com.karumi.kotlinsnapshot.matchWithSnapshot
import net.varionic.cloudbase.routing.GraphQLService
import org.koin.test.inject
import org.koin.test.mock.declareMock
import org.mockito.BDDMockito.given

class AppTest: TestBase() {
    @Test
    fun testQueryAllWorkbooks() {
        declareMock<WorkbookStore> {
            given(this.allWorkbooks).willReturn(mutableListOf(
                    Workbook("theBookId", "The Workbook Name")
            ))
        }

        val service: GraphQLService by inject()
        val result = service.engine.execute("""
            query {
                allWorkbooks {
                    uuid
                    name
                }
            }
        """.trimIndent())
        result.toSpecification().matchWithSnapshot()
    }
}
