import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin application project to get you started.
 */

val KOTLIN = "1.3.30"
val KTOR = "1.2.0-rc"
plugins {
    // Apply the Kotlin JVM plugin to add support for Kotlin on the JVM.
    id("org.jetbrains.kotlin.jvm").version("1.3.30")

    // Apply the application plugin to add support for building a CLI application.
    application
}

tasks.withType<KotlinCompile> {
    kotlinOptions {
        jvmTarget = "1.8"
    }
}

repositories {
    // Use jcenter for resolving your dependencies.
    // You can declare any Maven/Ivy/file repository here.
    jcenter()
}

dependencies {
    // Use the Kotlin JDK 8 standard library.
    implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8")

    // Use the Kotlin test library.
    testImplementation("org.jetbrains.kotlin:kotlin-test")

    // Use the Kotlin JUnit integration.
    testImplementation("org.jetbrains.kotlin:kotlin-test-junit")

    implementation("org.slf4j:slf4j-simple:1.8.0-beta4")
    implementation("io.ktor:ktor-server-core:$KTOR")
    implementation("io.ktor:ktor-server-netty:$KTOR")
    implementation("io.ktor:ktor-gson:$KTOR")
    implementation("org.koin:koin-ktor:2.0.0-GA4")

    implementation("com.graphql-java:graphql-java:12.0")

    implementation("org.jetbrains.kotlin:kotlin-script-runtime:$KOTLIN")
    implementation("org.jetbrains.kotlin:kotlin-script-util:$KOTLIN")
    implementation("org.jetbrains.kotlin:kotlin-compiler-embeddable:$KOTLIN")
    implementation("org.jetbrains.kotlin:kotlin-scripting-compiler-embeddable:$KOTLIN")

    implementation("org.jetbrains.exposed:exposed:0.13.7")
}

sourceSets["main"].resources.srcDir("../client/build")

tasks.named("processResources") {
    dependsOn(":webpack")
}

application {
    // Define the main class for the application.
    mainClassName = "net.varionic.cloudbase.AppKt"
}
